"""Add is_overnight_shift and break_duration_minutes to shifts table

Revision ID: e2d3a29b7890
Revises: 
Create Date: 2026-03-29 20:54:57.350647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2d3a29b7890'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('auth_user', 'role',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    # Add new columns with default values to maintain backward compatibility
    op.add_column('shifts', sa.Column('is_overnight_shift', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('shifts', sa.Column('break_duration_minutes', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shifts', 'break_duration_minutes')
    op.drop_column('shifts', 'is_overnight_shift')
    op.alter_column('auth_user', 'role',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###
